output "master_username" {
  value       = module.rds_cluster.master_username
  description = "Username for the master DB user"
  sensitive   = true
}

output "cluster_identifier" {
  value       = module.rds_cluster.cluster_identifier
  description = "Cluster Identifier"
}

output "arn" {
  value       = module.rds_cluster.arn
  description = "Amazon Resource Name (ARN) of the cluster"
}

output "endpoint" {
  value       = module.rds_cluster.endpoint
  description = "The DNS address of the RDS instance"
}

output "reader_endpoint" {
  value       = module.rds_cluster.reader_endpoint
  description = "A read-only endpoint for the Aurora cluster, automatically load-balanced across replicas"
}

output "port" {
  value       = module.rds_cluster.port
  description = "DB port"
}

output "dbi_resource_ids" {
  value       = module.rds_cluster.dbi_resource_ids
  description = "List of the region-unique, immutable identifiers for the DB instances in the cluster"
}

output "instance_endpoints" {
  value       = module.rds_cluster.instance_endpoints
  description = "List of DNS addresses for the DB instances in the cluster"
}

output "cluster_resource_id" {
  value       = module.rds_cluster.cluster_resource_id
  description = "The region-unique, immutable identifie of the cluster"
}

output "cluster_security_groups" {
  value       = module.rds_cluster.cluster_security_groups
  description = "Default RDS cluster security groups"
}

output "security_group_id" {
  value       = module.rds_cluster.security_group_id
  description = "Security Group ID"
}

output "security_group_arn" {
  value       = module.rds_cluster.security_group_arn
  description = "Security Group ARN"
}

output "security_group_name" {
  value       = module.rds_cluster.security_group_name
  description = "Security Group name"
}

output "activity_stream_arn" {
  value       = module.rds_cluster.activity_stream_arn
  description = "Activity Stream ARN"
}

output "activity_stream_name" {
  value       = module.rds_cluster.activity_stream_name
  description = "Activity Stream Name"
}

output "reserved_instance" {
  value       = module.rds_cluster.reserved_instance
  description = "All information about the reserved instance(s) if created."
}

output "db_access_security_group_id" {
  value       = join("", aws_security_group.allowed[*].id)
  description = "ID of the security group for use by services which need access to the DB"
}

output "database_user" {
  value       = local.database_username
  description = "Database username - either supplied or generated by module"
}

output "database_user_ssm_param_arn" {
  value       = lookup(module.store_write.arn_map, var.db_username_ssm_param_path, "")
  description = "Database username SSM param store item ARN"
}

output "database_password" {
  value       = var.database_password == "" ? join("", random_password.password[*].result) : var.database_password
  description = "Database password if generated by module"
  sensitive   = true
}

output "database_password_ssm_param_arn" {
  value       = lookup(module.store_write.arn_map, var.db_password_ssm_param_path, "")
  description = "Database user password SSM param store item ARN"
}

output "database_name" {
  # Can't use coalesce here because both values can be empty, but we want to output "" instead of null
  value       = var.database_name == null ? "" : var.database_name
  description = "Name of database created with instance"
}
